cmd:         "/home/yeahyay/Programming/lua/love2d/love"
name:        "Love 2d"
args:
  - "./"
sh:          true
cwd:         "{PROJECT_PATH}"
keymap:      ctrl-b
targets:
  "Kaitai Struct":
    cmd:     "ksc"
    name:    "Kaitai Struct"
    cwd:     "{FILE_ACTIVE_PATH}"
    args:
      - "-no-version-check"
      - "-v"
      - "-t lua"
      - "--outdir \"{FILE_ACTIVE_PATH}\""
      - "'{FILE_ACTIVE_NAME}'"
      # - "'{PROJECT_PATH}/src/Parsing/Kaitai_Struct/{FILE_ACTIVE_NAME}'"
    sh:      true
  "Windows":
    cmd:     "F:\\Programming\\Lua\\Love2D\\love-11.3-win64\\love"
    name:    "Love 2d"
    args:
      - "./"
    sh:      true
    keymap:  ctrl-b
  "Lizard":
    # cwd:   "{PROJECT_PATH}"
    cmd:     "lizard"
    name:    "Lizard"
    args:
      - "-l lua"
      - "./"
      - "-x\"*/lib/*\""
      - "-x\"*/DataStructures/*\""
      - "-x\"*__*\""
      - "-x\"Kaitai_Struct\""
      - "-x\"*PepperFish*\""
      - "-x\"./conf.lua\""
    sh:      true
    keymap:  ctrl-alt-shift-a
  "Lizard Duplicate":
    cmd:     "lizard"
    name:    "Lizard duplicate"
    args:
      - "--exclude \"input*\""
      - "-Eduplicate ./Feint_Engine/modules"
      # - "-x \"*/lib/*\" -x \"*\\lib\\\""
    sh:      true
    keymap:  ctrl-alt-shift-d

  "Gource":
    # cwd:   "{PROJECT_PATH}"
    cmd:     "gource"
    name:    "Gource"
    args:
      # - "-f"
      - "-1920x1080"
      - "--no-time-travel"
      - "--highlight-dirs"
      - "--key" # file extension key
      - "-a 0.005" # auto skip
      - "-s 0.25" # seconds per day
      - "-c 0.5" # time scale
      - "-e 0.05" # node elasticity
      - "-p 0.0005" # start position
      - "--camera-mode track"
      - "--follow-user Yeahyay"
      - "--max-user-speed 250"
      - "--user-friction 0.8"
    sh:      true
    keymap:  ctrl-alt-shift-g
